### ISSUE TITLE
Default bucket?

### ISSUE THREAD

**Issue by rpconroy** [NCAR/isd-s3#11]
Should we have a default bucket? It's annoying specifying it every time. This could be a module global, environment variable, or something else. 

There's also the question of which other defaults we could want. 
@tcram @DCSCHUS

**Comment by DCSCHUS** [comment]
I think specifying the default bucket as a environment variable by user might be the best option since staff outside of DECS may be using this tool.

**Comment by rpconroy** [comment]
A default bucket can be specified a few ways.

*Environment variable* - set `ISD_S3_DEFAULT_BUCKET` to desired bucket.

*Command line* - `python isd_s3 --default_bucket [bucket name]` or `python isd_s3 -db [bucket name]` 

*Config Module* -
```python 
import config
config.set_default_bucket('bucket_name')
```
*In .ini file*
```
....
[default]
bucket = bucket_name
....
```
