### ISSUE TITLE
Need to define required and optional metadata keys

### ISSUE THREAD

**Issue by DCSCHUS** [NCAR/isd-s3#17]
Possible keys:
Version
DatasetId
ObjectInventoryFields
Other?

**Comment by DCSCHUS** [comment]
DOI

**Comment by rpconroy** [comment]
https://docs.google.com/document/d/1rtbs962l09olw6lsMDDXlhenwrkCDMFDq4iI9hBt6aE/edit
The only Metadata being enforced by this tool are (when not already specified), 
`Uploading-account` - name of uploader
`Institution` - 'NCAR' 
`Content-Type` - Only for grib and netcdf files.

`Content-MD5` can be optionally added.
