### ISSUE TITLE
TypeError with s3_url

### ISSUE THREAD

**Issue by tcram** [NCAR/isd-s3#22]
Calling an action such as `list_buckets` raises the following TypeError:
```
[(NPL) ] [tcram@casper01 ~]$ isd_s3.py lb
Traceback (most recent call last):
  File "/glade/u/home/rdadata/bin/isd_s3.py", line 752, in <module>
    main(*sys.argv[1:])
  File "/glade/u/home/rdadata/bin/isd_s3.py", line 743, in main
    ret = do_action(args)
  File "/glade/u/home/rdadata/bin/isd_s3.py", line 692, in do_action
    return prog(**args_dict)
TypeError: list_buckets() got an unexpected keyword argument 's3_url'
```
I think the fix here is to remove `s3_url` from the global arguments in `_remove_common_args`.

**Comment by tcram** [comment]
Branched this out to the `fix-arg-error` branch

**Comment by rpconroy** [comment]
> I think the fix here is to remove s3_url from the global arguments in _remove_common_args.
Yep that's exactly right. It looks like I pushed a version without the fix.
