### ISSUE TITLE
checksum 

### ISSUE THREAD

**Issue by DCSCHUS** [NCAR/isd-s3#7]
get checksum of file

**Comment by rpconroy** [comment]
md5sum only works when the file has not been a multipart upload. 

When there's a multipart upload the object store computes an md5sum for each part, concatenates all of these strings, then takes the md5sum of that result. 

So, this makes doing checksums difficult. It would be easier to simply catch an error on upload. 

Nevertheless, I wrote a method to at least attempt to check the md5sum.

**Comment by DCSCHUS** [comment]
Thanks!
